### ISSUE TITLE
FPGA can't work with Problem2 

### ISSUE THREAD

**Issue by japoka410666** [yuyuranium/fpga-hw1#7]
With current src code, FPGA has behavior :
sw | led4 |    led5  |  led  |
--- |------|---------|------|
00 | blue |    blue   |0000 |
01 | red   | green   |1010 |
11 |   X    |    X       |1000 |
10 | white|white|1000|

Also, the spec doesn't have the input `rst`. I place it as `btn[3]` for testing.
When I click `rst` in `sw[00]` state, `led4` and `led5` will have a impulse  yellow light.

**Comment by WillyChennnn** [comment]
maybe led present little Indian ? for this pattern, the LED result is right ?

**Comment by yuyuranium** [comment]
The problem may be caused by the *active-low* reset. Since pressing the button on the FPGA is **HIGH**, changing the `rst` signal to *active-high* may help fix the problem for now.

**Comment by japoka410666** [comment]
I just test the new files. There are still several problems:
sw | Problems| correct feature
--- |-----|---|
00 | wrong light order (T1, T2): (G,R), (Y,Y), (R,Y), (Y,Y), (RR), (G,R), .... | led countdown|
01, 11, 10 | click btn[1] makes led = 1111, click btn[2] makes led = 0000| 1. btn[0]   2. changes are saved |

**Comment by japoka410666** [comment]
BTW, There are some DRC violation warning:

1. [DRC PDRC-153] Gated clock check: Net debouncer0/debounced_o_reg_LDC_i_1_n_0 is a gated clock net sourced by a combinational pin debouncer0/debounced_o_reg_LDC_i_1/O, cell debouncer0/debounced_o_reg_LDC_i_1. This is not good design practice and will likely impact performance. For SLICE registers, for example, use the CE pin to control the loading of data. (Click [here](https://support.xilinx.com/s/question/0D52E00006hpOKTSA2/gated-clock-warning?language=en_US) to see the explanation at  _BEST SOLUTION_ .)
2. [DRC ZPS7-1] PS7 block required: The PS7 cell must be used in this Zynq design in order to enable correct default configuration. (I can't understand this one)

**Comment by japoka410666** [comment]
Finally, _led_ successfully work. There are some further inspections for `sw==00` :
|light(T1, T2)|(G,R)|(Y,Y)|(R,Y)|(RR)|
|---|---|---|---|---|
|time length Ref|RG_length|X|Yellow_length|RR_legth|

(X means _led_ shows `0000` .)

I also find that if I change the switch from 00 to 01 too slowly, it will show (Y,Y) for a moment at the transition time and the RG time length will become `0000`.

**Comment by yuyuranium** [comment]
#13 fixes the problem.
